version: 2
jobs:
  build:
    docker:
      - image: openjdk:8-jdk
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Plugin.kt" }}-{{ checksum "buildSrc/src/main/kotlin/Lib.kt" }}
            - v2-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Plugin.kt" }}
            - v2-{{ checksum "build.gradle.kts" }}
            - v2-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
            - .gradle
          key: v2-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Plugin.kt" }}-{{ checksum "buildSrc/src/main/kotlin/Lib.kt" }}

      - run:
          name: Build jar-file
          command: ./gradlew shadowJar

      - run:
          name: Renaming and moving jar-file
          command: mv build/libs/*-all.jar build/musicbot-gplaymusic.jar

      - store-artifacts:
          path: build/musicbot-gplaymusic.jar
